# Generated by Django 2.0.1 on 2018-12-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181218_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='pictures',
            new_name='picture',
        ),
    ]
