# Generated by Django 2.0.1 on 2018-12-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181218_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom')], default=1, max_length=256),
            preserve_default=False,
        ),
    ]
